= Table.AddColumn(#"Reordered Columns",  "STATE", each if
[AREA_TITLE] =  "Alabama" then "AL"
else if [AREA_TITLE] = "Alaska" then "AK"
else if [AREA_TITLE] = "Arizona" then "AZ"
else if [AREA_TITLE] = "Arkansas" then "AR"
else if [AREA_TITLE] = "California" then  "CA"
else if [AREA_TITLE] = "Colorado" then  "CO"
else if [AREA_TITLE] = "Connecticut" then  "CT"
else if [AREA_TITLE] = "Delaware" then  "DE"
else if [AREA_TITLE] = "District of Columbia" then "DC"
else if [AREA_TITLE] = "Florida" then  "FL"
else if [AREA_TITLE] = "Georgia" then  "GA"
else if [AREA_TITLE] = "Hawaii" then  "HI"
else if [AREA_TITLE] = "Idaho" then "ID"
else if [AREA_TITLE] = "Illinois" then "IL"
else if [AREA_TITLE] = "Indiana" then "IN"
else if [AREA_TITLE] = "Iowa" then "IA"
else if [AREA_TITLE] = "Kansas" then "KS"
else if [AREA_TITLE] = "Kentucky" then "KY"
else if [AREA_TITLE] = "Louisiana" then "LA"
else if [AREA_TITLE] = "Maine" then "ME"
else if [AREA_TITLE] = "Maryland" then "MD"
else if [AREA_TITLE] = "Massachusetts" then "MA"
else if [AREA_TITLE] = "Michigan" then "MI"
else if [AREA_TITLE] = "Minnesota" then "MN"
else if [AREA_TITLE] = "Mississippi" then "MS"
else if [AREA_TITLE] = "Missouri" then "MO"
else if [AREA_TITLE] = "Montana" then "MT"
else if [AREA_TITLE] = "Nebraska" then "NE"
else if [AREA_TITLE] = "Nevada" then "NV"
else if [AREA_TITLE] = "New Hampshire" then "NH"
else if [AREA_TITLE] = "New Jersey" then "NJ"
else if [AREA_TITLE] = "New Mexico" then "NM"
else if [AREA_TITLE] = "New York" then "NY"
else if [AREA_TITLE] = "North Carolina" then "NC"
else if [AREA_TITLE] = "North Dakota" then "ND"
else if [AREA_TITLE] = "Ohio" then "OH"
else if [AREA_TITLE] = "Oklahoma" then "OK"
else if [AREA_TITLE] = "Oregon" then "OR"
else if [AREA_TITLE] = "Pennsylvania" then "PA"
else if [AREA_TITLE] = "Rhode Island" then "RI"
else if [AREA_TITLE] = "South Carolina" then "SC"
else if [AREA_TITLE] = "South Dakota" then "SD"
else if [AREA_TITLE] = "Tennessee" then "TN"
else if [AREA_TITLE] = "Texas" then "TX"
else if [AREA_TITLE] = "Utah" then "UT"
else if [AREA_TITLE] = "Vermont" then "VT"
else if [AREA_TITLE] = "Virginia" then "VA"
else if [AREA_TITLE] = "Washington" then "WA"
else if [AREA_TITLE] = "West Virginia" then "WV"
else if [AREA_TITLE] = "Wisconsin" then "WI"
else if [AREA_TITLE] = "Wyoming" then "WY"
else if [AREA_TITLE] = "Puerto Rico" then "PR"
else if [AREA_TITLE] = "Virgin Islands" then "VI"
else if [AREA_TITLE] = "Guam" then "GU"
else "state not found")